version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
